apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: house-api
resources:
 - namespace.yaml
 - lights.yaml
 - weather.yaml
configMapGenerator:
  - name: house-api-weather-config
    literals:
      - redis-url="dev-weather-forecast-cache-internal-service"
      - redis-port=6379
      - lat=36.2162
      - lon=-81.6777
